name: Generate site and push to GitHub pages branch

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  generate_and_commit:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Checkout website repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master
  
      - name: Build and install Pushpin
        run: |
          ls
          cargo build --release
          PUSHPIN_PATH=$(pwd)/target/release/pushpin
          echo "PUSHPIN_PATH=$PUSHPIN_PATH" >> $GITHUB_ENV

      - name: Run Pushpin
        run: |
          ls
          cd docs
          $PUSHPIN_PATH generate
          ls
          find .

      - name: Commit changes and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git checkout -b gh-pages
          git commit -m "Automated file generation"
          git push https://${{ secrets.ACCESS_TOKEN }}@github.com/tedbauer/pushpin HEAD:gh-pages --force